"""PHP code chunker.

Produces method-level chunks from ParsedSection objects generated by
PhpCodeParser. Each chunk is prefixed with class context so that the
embedded text is self-contained without the surrounding source file.
"""

from __future__ import annotations

from odyssey_rag.ingestion.chunkers.base import BaseChunker, Chunk, count_tokens
from odyssey_rag.ingestion.parsers.base import ParsedSection


def _class_context_prefix(section: ParsedSection) -> str:
    """Build a short class-context prefix for a chunk."""
    php_class = section.metadata.get("php_class", "")
    module_path = section.metadata.get("module_path", "")
    parts = []
    if php_class:
        parts.append(f"Class: {php_class}")
    if module_path:
        parts.append(f"File: {module_path}")
    if parts:
        return "\n".join(parts) + "\n\n"
    return ""


class PhpCodeChunker(BaseChunker):
    """Method-level chunker for PHP source code.

    Chunking strategy:
    1. Each ParsedSection from PhpCodeParser (class_overview, individual
       method, constants_properties) maps to **one chunk** by default because
       methods are typically small.
    2. If a method body exceeds ``max_tokens``, it is split at logical PHP
       block boundaries (blank lines), with overlap.
    3. Every chunk is prefixed with the class name + file path for context.
    """

    def chunk(self, sections: list[ParsedSection]) -> list[Chunk]:
        """Split PHP sections into token-bounded chunks.

        Args:
            sections: Ordered list of ParsedSection objects from PhpCodeParser.

        Returns:
            Ordered list of Chunk objects with sequential ``chunk_index`` values.
        """
        chunks: list[Chunk] = []
        idx = 0

        for section in sections:
            prefix = _class_context_prefix(section)
            content = section.content
            full_text = prefix + content

            if count_tokens(full_text) <= self.max_tokens:
                chunks.append(
                    Chunk(
                        content=full_text,
                        token_count=count_tokens(full_text),
                        section=section.section,
                        subsection=section.subsection,
                        chunk_index=idx,
                        metadata=dict(section.metadata),
                    )
                )
                idx += 1
            else:
                # Large method: split at blank-line boundaries with overlap
                sub_chunks = self._split_code_block(full_text, prefix, section)
                for sc in sub_chunks:
                    sc.chunk_index = idx
                    idx += 1
                chunks.extend(sub_chunks)

        return chunks

    def _split_code_block(
        self, full_text: str, prefix: str, section: ParsedSection
    ) -> list[Chunk]:
        """Split a large code block at blank-line boundaries."""
        lines = full_text.splitlines()
        result_chunks: list[Chunk] = []
        current_lines: list[str] = []
        current_tokens = 0
        overlap_lines: list[str] = []

        for line in lines:
            line_tokens = count_tokens(line)

            if (
                current_tokens + line_tokens > self.max_tokens
                and current_lines
                and line.strip() == ""
            ):
                # Flush on a blank-line boundary
                chunk_text = "\n".join(current_lines)
                result_chunks.append(
                    Chunk(
                        content=chunk_text,
                        token_count=count_tokens(chunk_text),
                        section=section.section,
                        subsection=section.subsection,
                        chunk_index=0,  # Will be overwritten by caller
                        metadata=dict(section.metadata),
                    )
                )

                # Overlap: take last N lines
                overlap_count = max(1, self.overlap_tokens // 10)
                overlap_lines = current_lines[-overlap_count:]
                current_lines = list(overlap_lines)
                current_tokens = sum(count_tokens(l) for l in current_lines)
            else:
                current_lines.append(line)
                current_tokens += line_tokens

        if current_lines:
            chunk_text = "\n".join(current_lines)
            result_chunks.append(
                Chunk(
                    content=chunk_text,
                    token_count=count_tokens(chunk_text),
                    section=section.section,
                    subsection=section.subsection,
                    chunk_index=0,
                    metadata=dict(section.metadata),
                )
            )

        return result_chunks if result_chunks else [
            Chunk(
                content=full_text,
                token_count=count_tokens(full_text),
                section=section.section,
                subsection=section.subsection,
                chunk_index=0,
                metadata=dict(section.metadata),
            )
        ]
